- op: replace
  path: /spec/template/spec/containers/0/env/0/value
  value: blue
- op: replace
  path: /spec/template/spec/containers/0/image
  value: ocp-registry-quay-quay.apps.ocp4.sandbox526.opentlc.com/admin/bgd:dev
